### ISSUE TITLE
Provide more documentation about JSON structure

### ISSUE THREAD

**Issue by Novitoll** [NUKnightLab/TimelineJS#805]
Please anyone improve the doc about JSON structure: `startDate`, `endDate` etc. how they should look like if you have several dates (array, string etc). Also please add examples with code source.

**Comment by danabnormal** [comment]
I found the examples provided covered everything I needed, including the JSON structure. Have you had a peek in https://github.com/NUKnightLab/TimelineJS/tree/master/examples ?

**Comment by JoeGermuska** [comment]
we are tapering off development on this version of Timeline as we are in a beta phase for the rewritten [TimelineJS3](https://github.com/NUKnightLab/TimelineJS3). One of our priorities is better and more findable [documentation](http://timeline3.knightlab.com/docs/index.html) including [this on JSON](http://timeline3.knightlab.com/docs/json-format.html)

Take a look, try out TimelineJS3 (we think it's in great shape, but we want to have a gradual transition since TimelineJS is our most popular tool).
